config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :delete_sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true
  def self.overdue
    all.where("due_date < ? and completed = ?", Date.today, false)
  end

  def self.due_today
    all.where("due_date = ?", Date.today)
  end

  def self.due_later
    all.where("due_date > ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos
  validates :first_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render :index
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password_digest])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid,Please try again"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = current_user.todos.find(id)
    render plain: todo.to_pleasant
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(todo_text: todo_text, due_date: due_date, completed: false, user_id: current_user.id)
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password_digest],
    )
    if new_user.save
      session[:current_user_id] = new_user.id
      flash[:success] = "Signed Up successfully & Logged In"
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="HomeTitle">Welcome to my Todo Page</h1>
<h3 class="HomeAuthentication">
  If you are a new user,<%= link_to "SignUp here", new_user_path%>
</h3>
<h3 class="HomeAuthentication">
  If you are existing user,<%= link_to "SignIn here", new_sessions_path%>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name%>
        <%= link_to "SignOut", delete_sessions_path,method: "delete"%>
      </p>
    <% end %>
    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <% if flash[:success] %>
      <p class="Flash-success">
        <%= flash[:success]%>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.erb
<section class="TodoSection">
  <div class=TodoSectionTitle>
    <p class="TodoSectionTitle-text"><%= section_title%></p>
    <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %>/<%= todos.count %></p>
  </div>
  <ul>
    <% todos.all.each do |todo|%>
    <li class="TodoItem">
      <div class="TodoItem-container">
        <input class="TodoItem-checkbox" type="checkbox">
        <p class="TodoItem-text"><%= todo.todo_text %></p>
        <% if show_dueDate %>
          <p class="Todoitem-dueDate"><%= todo.due_date.to_s(:short) %></p>
        <% end %>
        <img class="TodoItem-deleteicon" src="delete.png" alt="deleteicon" height=16px width=16px></a>
      </div>
    </li>
    <% end %>
  </ul>
</section>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class=TodoSectionTitle>
    <p class="TodoSectionTitle-text"><%= section_title%></p>
    <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %>/<%= todos.count %></p>
  </div>
  <ul>
    <% todos.all.each do |todo|%>
    <li class="TodoItem">
      <div class="TodoItem-container">
        <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
          <%=check_box_tag("completed",nil,todo.completed,{onclick: "this.form.submit()",class: "TodoItem-checkbox"})%>
        <% end %>
        <p class= <%= todo.completed ? "TodoItem-textCompleted" : "TodoItem-text" %>><%=todo.todo_text%></p>
        <% if show_dueDate %>
          <p class="TodoItem-dueDate"><%= todo.due_date.to_s(:short) %></p>
        <% end %>
        <%= form_with(url: "/todos/#{todo.id}", method: "DELETE") do %>
          <%= image_submit_tag("delete.png",class: "TodoItem-deleteicon",alt: "deleteicon")%>
        <% end %>
      </div>
    </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
    <article>
      <h1 class="TodoPage-title">My To-do List</h1>
      <%= form_with(url: "/todos", method: "POST",class: "AddTodo") do %>
        <%= text_field_tag("todo_text","",placeholder: "what's next?",class: "AddTodo-text",autofocus: "autofocus")%>
        <%= date_field_tag("due_date",nil,class: "AddTodo-date")%>
        <%= button_tag("Add",type: "submit",class: "AddTodo-button")%>
      <% end %>
      <%= render partial: "todo-section", locals: {
        section_title: "Overdue", todos: @todos.overdue, show_dueDate: true
        } %>
      <%= render partial: "todo-section", locals: {
        section_title: "Due Today", todos: @todos.due_today, show_dueDate: false
        } %>
      <%= render partial: "todo-section", locals: {
        section_title: "Due Later", todos: @todos.due_later, show_dueDate: true
        } %>
    </article>
  </main>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome New user!</p>
<section class="usersNew">
  <%= form_with url: users_path do |form|%>
    <div class="Form-section">
      <p class="ForInput-label">First name: </p>
      <%= form.text_field :first_name,autofocus: "autofocus",class: "FormInput"%>
    </div>
    <div class="Form-section">
      <p class="ForInput-label">Last name: </p>
      <%= form.text_field :last_name, class: "FormInput"%>
    </div>
    <div class="Form-section">
      <p class="ForInput-label">email: </p>
      <%= form.email_field :email, class: "FormInput"%>
    </div>
    <div class="Form-section">
      <p class="ForInput-label">password: </p>
      <%= form.password_field :password_digest, class: "FormInput"%>
    </div>
    <%= form.submit "SignUp!",class: "SubmitButton"%>
  <% end %>
</section>